### ISSUE TITLE
Сannot import name '_imaging' from 'PIL' 

### ISSUE THREAD

**Issue by kaageol** [agisoft-llc/metashape-scripts#103]
An error occurs when running the script automatic_masking.py:
Error: cannot import name '_imaging' from 'PIL' (C:\Program Files\Agisoft\Metashape Pro\python\lib\site-packages\PIL\__init__.py)

**Comment by PolarNick239** [comment]
Hi, please try to update the Pillow (i.e. PIL) library:

```"%programfiles%\Agisoft\Metashape Pro\python\python.exe" -m pip install -U Pillow``` (it should be executed from CMD terminal, and probable CMD terminal should be launched with administrator privileges)

Then please try again. If the problem persists, please provide output of the following command:

```"%programfiles%\Agisoft\Metashape Pro\python\python.exe" -m pip freeze```
