### ISSUE TITLE
footprints_to_shapes.py not working with Film cameras

### ISSUE THREAD

**Issue by Chased11111** [agisoft-llc/metashape-scripts#108]
Hello,
I am having some issues with making this script work with aerial imagery with fiducial markers (FM). It does work but it creates small polygons (like 20x20 cm) I guess there is some issue with transformation of the FM coordinates to CRS but I cant seem to get it to work correctly.

Help would be appriciated.

**Comment by PolarNick239** [comment]
Hello,
please share a project-reproducer to support@agisoft.com with steps to reproduce, so we were able to reproduce and investigate the problem. Probably small part of the project will be enough - just make sure that it can reproduce the problem.

**Comment by PolarNick239** [comment]
Hi, @Chased11111 
script was updated https://github.com/agisoft-llc/metashape-scripts/blob/master/src/footprints_to_shapes.py - can you please try again the new version?

**Comment by Chased11111** [comment]
> Hi, @Chased11111 script was updated https://github.com/agisoft-llc/metashape-scripts/blob/master/src/footprints_to_shapes.py - can you please try again the new version?

thanks for the quick response! works like a charm now
