### ISSUE TITLE
Metashape footprint script empty shapefile

### ISSUE THREAD

**Issue by gifro10** [agisoft-llc/metashape-scripts#12]
I have Metashape Pro 1.5.1  and recently loaded the image footprints script.  The menu shows up fine, and when the script runs a footprints group gets created in the left menu, but it's empty and exporting leads to an empty shapefile.  Is there any customization to the script that is necessary, and do all images have to be aligned with a mesh and point cloud for this script to do its job properly?  Thank you for the development efforts

**Comment by PolarNick239** [comment]
Footprints script tries to intersect four rays per aligned camera (one ray per image corner) with observable surface. I.e. if project has model - script intersects rays with it. If there is no model but project has dense cloud - script intersects rays with it. If there is either no model and no dense cloud - script intersects rays with tie points.

So yes, script can generate footprints only for images that were aligned and it will be able to intersect corner rays only if project has model/dense cloud/tie points.

**Comment by PolarNick239** [comment]
Please feel free to reopen issue if you still have the problem.
