### ISSUE TITLE
split_in_chunks_dialog.py doesn't split the chunk?

### ISSUE THREAD

**Issue by ahalota** [agisoft-llc/metashape-scripts#15]
I tried running this script in Metashape 1.5.1, but it seems to just duplicate my chunk (I set a 2 x 2 split as test), with all photos in each one.

I'm looking through the code and can't figure out at what point it actually does any splitting. I see it is recalculating the region, but it seems to have no effect?

**Comment by PolarNick239** [comment]
Hi!
Please take a look [here](https://github.com/agisoft-llc/metashape-scripts/blob/67f8fd0c1da96d078403569c36c12fc5fbd8e0e4/src/split_in_chunks_dialog.py#L241-L255) - splitting done via region bounding box subdivision into 4 parts (in case of 2x2). For processing of each region part - separate chunk will be created.

**Comment by PolarNick239** [comment]
Please feel free to reopen issue if you still have the problem.
