### ISSUE TITLE
Multi-frame chunk, script blocked in the activ frame

### ISSUE THREAD

**Issue by paulinescho** [agisoft-llc/metashape-scripts#18]
Hello,

I want to create a small script to export estimated coordinates from a multi-frame chunk using the function saveReference. So I created a loop as you can see in the following script. The problem is I only obtain the coordinates of the active frame. It create the right number of file but they all have the same coordinates of the frame that is open in Metashape.

I can find anything about that problem so I'll be glad if someone as an idea about this issue.

import Metashape as ms
import os
doc = ms.app.document
path="suivi_reperes/"
i=0
for frame in doc.chunks[5].frames: #I'm only interested in this chunk number 5
	file_name=path+'reperes_t'+str(i)	frame.saveReference(file_name,PhotoScan.ReferenceFormatCSV,items=PhotoScan.ReferenceItemsMarkers,columns="n,[u|v|w],")
	i+=1

**Comment by PolarNick239** [comment]
Hi,

As you noted saveReference for markers exports coordinates from the active frame, this is design-restriction of current API implementation. But you can use simple workaround - make current frame active before calling saveReference:

```python
import Metashape as ms
import os
doc = ms.app.document
path="suivi_reperes/"
i=0
chunk = doc.chunks[5] #I'm only interested in this chunk number 5
active_frame_before = chunk.frame
for frame in chunk.frames:
    file_name=path+'reperes_t'+str(i)
    chunk.setFrame(frame)
    frame.saveReference(file_name, PhotoScan.ReferenceFormatCSV, items=PhotoScan.ReferenceItemsMarkers, columns="n,[u|v|w],")
    i+=1
chunk.setFrame(active_frame_before) # returning active frame back
```

**Comment by PolarNick239** [comment]
Please feel free to reopen issue if you still have the problem.
