### ISSUE TITLE
Way to remove/replace custom menu items?

### ISSUE THREAD

**Issue by ahalota** [agisoft-llc/metashape-scripts#20]
Is there a way to remove existing menu items? While debugging it gets messy if I keep uploading them several times.

Ideally just hold on to a reference for the newly added item and delete it with QtWidgets would work? Not sure how to find that though for an item I've added.

**Comment by PolarNick239** [comment]
Yes, this is good idea, thanks. ```Metashape.app.removeMenuItem(label)``` will be added in 1.6.2 release.
