### ISSUE TITLE
How to place markers with python scripts?

### ISSUE THREAD

**Issue by poxiao2** [agisoft-llc/metashape-scripts#24]
I know how to add markers, but I have no idea how to place markers on the photos.

**Comment by PolarNick239** [comment]
Hi!

See ```Metashape.Utils.createMarkers(chunk, projections)``` in [Python API](https://www.agisoft.com/pdf/metashape_python_api_1_6_0.pdf).

projections - list of (Camera, Target) tuples. See also this [topic](https://www.agisoft.com/forum/index.php?topic=7446.0) on forum (for example to learn more about Target.radius).

**Comment by PolarNick239** [comment]
Feel free to reopen the issue if needed.

**Comment by poxiao2** [comment]
thanks，already solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nikolai Poliarnyi"<notifications@github.com&gt;; 
发送时间: 2020年9月30日(星期三) 晚上8:38
收件人: "agisoft-llc/metashape-scripts"<metashape-scripts@noreply.github.com&gt;; 
抄送: "破晓"<3408699495@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [agisoft-llc/metashape-scripts] How to place markers with python scripts? (#24)





 
Hi!
 
See Metashape.Utils.createMarkers(chunk, projections) in Python API.
 
projections - list of (Camera, Target) tuples. See also this topic on forum (for example to learn more about Target.radius).
