### ISSUE TITLE
ExportPoints in Metashape

### ISSUE THREAD

**Issue by kaichand9** [agisoft-llc/metashape-scripts#25]
Can someone help me in exporting clipped point cloud using python code in Metashape. I am using 1.6.4 version of Agisoft

**Comment by PolarNick239** [comment]
Hi,

Please refer to [Python API](https://www.agisoft.com/pdf/metashape_python_api_1_6_4.pdf) - there are ```exportPoints(...)``` function, so:

If you need to export Dense Cloud points clipped to bounding box (region):

```python
Metashape.app.document.chunk.exportPoints(path="...dense_cloud_clipped.ply", source_data=Metashape.DenseCloudData, clip_to_boundary=True)
```

If you need to export Tie Points (sparse cloud) clipped to bounding box (region):

```python
Metashape.app.document.chunk.exportPoints(path="...tie_points_clipped.ply", source_data=Metashape.PointCloudData, clip_to_boundary=True)
```

**Comment by kaichand9** [comment]
Thanks for suggestions
I wanted to export in .las file

I am using metashape 1.6.4 version.

Giving error in export format. I tried following - las, asprs las, pointformatlas. But not taking giving some error

**Comment by PolarNick239** [comment]
Can you please provide error message from console?

**Comment by kaichand9** [comment]
Ok
![image](https://user-images.githubusercontent.com/39769675/99980318-1db75880-2dce-11eb-901e-7405bd8ba658.png)

**Comment by PolarNick239** [comment]
It is due to a missing comma in the previous line: ```confidence:True```.

After other fixes w.r.t. ```exportPoints``` signature in [Python API](https://www.agisoft.com/pdf/metashape_python_api_1_6_4.pdf):

```python
import Metashape
import os

doc = Metashape.app.document
chunk = doc.chunk

path = Metashape.app.getSaveFileName("Export Points")

export_point_config = {
'binary': True,
'save_normals': True,
'save_colors': True,
'save_confidence':True,
'format': Metashape.PointsFormatLAS,
}

chunk.exportPoints(path, **export_point_config)
```

**Comment by kaichand9** [comment]
Highly appreciate your help. 
Script is working fine now. Exporting but I need to define format .LAS (Dense.las) while exporting otherwise coming without extention (Dense). Also projection get changed to Geographic projection... Again thanks for help. Searching option for projection = CRS

**Comment by PolarNick239** [comment]
Do you want to export in Local Coordinates like via GUI dialog? If so:

```python
import Metashape
import os

doc = Metashape.app.document
chunk = doc.chunk

path = Metashape.app.getSaveFileName("Export Points")

export_point_config = {
'binary': True,
'save_normals': True, # changed
'save_colors': True, # changed
'save_confidence':True, # changed
'format': Metashape.PointsFormatLAS, # changed
'crs': Metashape.CoordinateSystem('LOCAL_CS["Local Coordinates(m)",LOCAL_DATUM["Local Datum",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]'),
}

chunk.exportPoints(path, **export_point_config)
```

**Comment by kaichand9** [comment]
Thanks for help. Yes I want to export like GUI. But when export using GUI it take default projection in which I have done processing in metashape
Just after adding photos and processing I have defined projection system (WGS to EPSG -20355), then why it is asking to re-define projection again while exporting Point cloud using python. I just want projection to be exported in which I have done all the processing., Appreciate your help

**Comment by PolarNick239** [comment]
Then you can use ```chunk.crs```:

```python
import Metashape
import os

doc = Metashape.app.document
chunk = doc.chunk

path = Metashape.app.getSaveFileName("Export Points")

export_point_config = {
'binary': True,
'save_normals': True,
'save_colors': True,
'save_confidence':True,
'format': Metashape.PointsFormatLAS,
'crs': chunk.crs, # changed
}

chunk.exportPoints(path, **export_point_config)
```

**Comment by kaichand9** [comment]
Thanks mate. 
Script is working fine. Appreciate your support
