### ISSUE TITLE
Align model to model - Registration attribute error

### ISSUE THREAD

**Issue by jnhb2** [agisoft-llc/metashape-scripts#27]
Hello,
I have the following error : AttributeError: module 'open3d' has no attribute 'registration' just after a clean install. 
Has registration moved to open3d.pipelines ?

Thanks

**Comment by PolarNick239** [comment]
Hi!

Please try the updated script, does it work for you?

**Comment by jnhb2** [comment]
Yes the updated script works perfectly, thanks !

**Comment by PolarNick239** [comment]
Nice :)
