### ISSUE TITLE
Export all depth map levels

### ISSUE THREAD

**Issue by Jordi-Gene-Mola** [agisoft-llc/metashape-scripts#28]
Hi,
The line code "depth = chunk.depth_maps[camera].image()" gets the depth map level 1. How can I get all depth map levels?
Thank you in advance :)

**Comment by PolarNick239** [comment]
Hi,

Just use level number as an argument to image (zero level is the most detailed):

```python
level = 0
depth_level = chunk.depth_maps[camera].image(level)
```

**Comment by Jordi-Gene-Mola** [comment]
Thank you for the rapid response @PolarNick239
I have tried it, but it pops up an error saying that image() takes no arguments (1 given). On which version of metashape it supossed to work? I am using V1.5.2
Best regards,
Jordi

**Comment by PolarNick239** [comment]
Oh, yes, it was introduced in version 1.5.3. And if the depth map doesn't have a specified level - the image() will return None.

**Comment by PolarNick239** [comment]
Please feel free to reopen the issue if you still have the problem.
