### ISSUE TITLE
A project will multiple chunks will be deleted except the current chunk

### ISSUE THREAD

**Issue by PeterJared** [agisoft-llc/metashape-scripts#3]
If we have a project with multiple chunks and we set the script as "merge back" it will delete all chunks of the project, regardless they are the ones created for the split or not.
This can be even more problematic if we have set also the option "autosave" and the deletion of the rest of chuks can not be reversed.
This can be obviously a nasty surprise for some users with complex projects, as all chucks of the project will disappear except the one being processed.
Mi recommendation is warn about it in the script menu, or simply only delete the chuks created for the split process and not everything else.

**Comment by PolarNick239** [comment]
Thanks for reporting this. Sorry if you lost processing results in those chunks.

Now script should not affect other chunks.

Please feel free to re-open the issue if needed.
