### ISSUE TITLE
python script of the full 3d reconstruction process

### ISSUE THREAD

**Issue by lith0613** [agisoft-llc/metashape-scripts#33]
Hi, can you share a script of the full process for 3d reconstruction. Maybe the functions are as follows:
1) In the tool panel -> Workflow → add photos (from a folder)

2) In the tool panel -> Workflow -> align photos :

3) In the tool panel -> Workflow -> Build dense cloud :

4) In the tool panel -> Workflow -> Build Mesh:

5) In the tool panel -> Workflow -> Build texture:

6) File → Export → Export mesh→ Export JPEG / TIFF / PNG

or give some detailed explannation for how to use the python API to finish these functions ?

Thanks !

**Comment by PolarNick239** [comment]
Hi, we published a sample script - https://github.com/agisoft-llc/metashape-scripts/blob/master/src/samples/general_workflow.py
