### ISSUE TITLE
Copy_bounding_box.py will malfunction if the project has unrelated multiple chunks

### ISSUE THREAD

**Issue by PeterJared** [agisoft-llc/metashape-scripts#4]
The script seems to work in the way that we select and open a chunk. Now If we use the script it will copy the bounding box of any other existing Chunk in the project.
The only way it works OK is if the project only has two Chunks, the origin and a compatible destiny. 

If the project has any other unrelated Chunk it generates multiple problems:
- The script will paste on all them the bounding boxes,  no matter his number. Not only that, multiple unrelated Chucks in some way confuses the script and paste a incorrect identical bounding box to all Chunks, even to the original Chunk. That means that if we don't notice it and save we will have all Chunks with a identical incorrect bounding Box.

My suggestion is:
- If any solution is expensive at least warn about it in the instructions, script or info dialogue.
- But obviously the ideal solution would be that we can define what is the destiny of the pasted bounding box instead being pasted everywhere. This could be done with a double operation, copy and then paste (with dialogue or two separated scripts).
- Or as alternative that only paste the original bounding box in the selected Chucks, and leave intact anything else. In this case, we select and open a Chunk and we select (but don't open) the destiny Chuck. Then the script would copy the bounding box of the opened Chunk over the selected Chunk.

**Comment by PolarNick239** [comment]
New script provides possibility to choose the source chunk and destination chunks. Does it work good for you?

**Comment by PeterJared** [comment]
That would be perfect!

**Comment by PeterJared** [comment]
When running the script appears a message saying "run script failed". The scene is not modified in any way.

**Comment by PeterJared** [comment]
Thanks, it works nicely!

**Comment by PeterJared** [comment]
solved!
