### ISSUE TITLE
split in chunks script not working

### ISSUE THREAD

**Issue by harryalp** [agisoft-llc/metashape-scripts#40]
Hello there, 

I am a newbie to using scripts,

I have 1250 photos to proecess and to prepare DEM and Orthophoto however since my hardware limits me up I wanted to split my work into chunks to work fluently without any crashes

I aligned all the photos firstly and then I used the script split in chunks however split in chunks command only does duplicate my dataset but nothing all

I am using Agisoft Metashape 1.8

Any help would be appreciated .

**Comment by PolarNick239** [comment]
Hi,

please check regions in those duplicated chunks. Each eegion should be a sub-space of the original region - so further processing should be done only on subregion in each chunk.
