### ISSUE TITLE
Error: module 'rembg.bg' has no attribute 'get_model'

### ISSUE THREAD

**Issue by ttsesm** [agisoft-llc/metashape-scripts#41]
Hi,

I am trying to use the `automatic_masking` script, however while the installation procedure went smoothly when I tried to run the script on my images I got the following error message:

```
Error: module 'rembg.bg' has no attribute 'get_model'
```
Any idea how to resolve it?

**Comment by PolarNick239** [comment]
Hi, thanks for reporting this!

The simplest fix is to use old rembg 1.0.27 - see [updated](https://github.com/agisoft-llc/metashape-scripts/commit/fdd6e6b4d5058c6cb79e29640f57ce49fa133019) installation instructions.

automatic_masking.py script is very sensitive to changes in rembg because it relies on its inner details - to achieve fast processing.

**Comment by ttsesm** [comment]
Hi @PolarNick239,

Thanks for the feedback. Yes, I imagined that it would be something like that. Ok, this error seems to be gone but now I am getting the following:
```
2022-03-24 12:05:22 Downloading u2net.pth to /home/ttsesm/.u2net: 0.00iB [00:00, ?iB/s]
2022-03-24 12:05:22 Downloading u2net.pth to /home/ttsesm/.u2net: 2.15kiB [00:00, 7.64MiB/s]
2022-03-24 12:05:23 
2022-03-24 12:05:23 Downloading u2net.pth to /home/ttsesm/.u2net: 0.00iB [00:00, ?iB/s]
2022-03-24 12:05:23 Downloading u2net.pth to /home/ttsesm/.u2net: 2.15kiB [00:00, 2.06MiB/s]
2022-03-24 12:05:23 
2022-03-24 12:05:23 Downloading u2net.pth to /home/ttsesm/.u2net: 0.00iB [00:00, ?iB/s]
2022-03-24 12:05:23 Downloading u2net.pth to /home/ttsesm/.u2net: 2.15kiB [00:00, 798kiB/s]
2022-03-24 12:05:23 Error: invalid load key, '<'.
```

**Comment by PolarNick239** [comment]
Old u2net model seems to be deleted from google drive. It worked for me because it was cached locally on my drive.

I updated script so that it works now with fresh rembg==2.0.10. Can you please reinstall it and try once again? (with fresh automatic_masking.py script)

**Comment by ttsesm** [comment]
Thanks, it works now. 

One more question, how I can call the script from the python api. At the moment, I am having the following procedure:
```
photos = find_files(image_folder, "png, jpg, jpeg, tif, tiff, PNG, JPG")

doc = Metashape.Document()
doc.save(output_folder + '/project.psx')

chunk = doc.addChunk()

chunk.addPhotos(photos)
doc.save()
print(str(len(chunk.cameras)) + " images loaded")

#------> call the masking script here

chunk.matchPhotos()
doc.save()
```

**Comment by PolarNick239** [comment]
Nice! :)

Call [this](https://github.com/agisoft-llc/metashape-scripts/blob/0303be55a87704a19417d0bdec46a6b4da15e1b3/src/automatic_masking.py#L45) function:

```python
generate_automatic_background_masks_with_rembg(chunk)
```

Note that when you will try to import it like this:
```python
from automatic_masking import generate_automatic_background_masks_with_rembg
```
it will also evaluate [these lines](https://github.com/agisoft-llc/metashape-scripts/blob/0303be55a87704a19417d0bdec46a6b4da15e1b3/src/automatic_masking.py#L153-L155) (binding the script function to button **Scripts->Automatic...**), but if you don't run under GUI - you may want to delete them.

**Comment by ttsesm** [comment]
Perfect, thanks a lot for the feedback.
