### ISSUE TITLE
network_processing.py is incompatible with 1.8.4.14671

### ISSUE THREAD

**Issue by jedfrechette** [agisoft-llc/metashape-scripts#52]
line 120 raises the exception:

`AttributeError: 'Metashape.NetworkClient' object has no attribute 'resumeBatch'

I haven't tested older versions, but according to the release notes that method was removed in 1.8.0 so presumably it's been broken for the entire 1.8 series.

setBatchPaused seems to be the replacement for this method and changing it to use that fixes the issue.

**Comment by Vineg** [comment]
@jedfrechette Thanks for reporting the issue! Fixed it.
