### ISSUE TITLE
Export height map from depth map.

### ISSUE THREAD

**Issue by YueyueBird-su** [agisoft-llc/metashape-scripts#60]
Hi, 
as the title says, how do I convert the depth map to height map?

I tried using altoff + depth, but it doesn't seem to be quite right./(ㄒoㄒ)/~~

**Comment by PolarNick239** [comment]
Hi,

please be more specific what data do you have on input, and what output format do you want to generate?

What is altoff + depth?

What was wrong with results of that attempt?

**Comment by YueyueBird-su** [comment]
Thank you for your reply，

The data I use is satellite images of RPC camera model.

After generating **F32 depth map** using _“export_depth_maps_dialog.py”_, the depth of each image pixel is known. 

But I want to get the height map corresponding to **each view image** like DEM. 

By observing, I found that the difference between DEM and depth map in the same area is about the altitude offset (alt_off) parameter in the RPC model. So I tried to use alt_off and depth_map to get the height maps of different viewpoint images.

In fact, the depth map is the distance from the ground point to the satellite, while the height map is the altitude of the Earth's surface. **How can I get the correct altitude map?**

**Comment by PolarNick239** [comment]
Why do you need DEM-like image but from the sattelite point of view?

There are no ready solution for this task, in general case standard DEM is used. You can try to write python script - something like this:

1) Generate dense point cloud from depth maps
2) Create empty result_image (filled with zeros)
3) For each point ```p``` from point cloud estimate ```px``` (pixel-projection of ```p```) and write altitude to result_image: ```result_image[px] = p.z```
4) Interpolate values in result_image
5) result_image is what you need

Note that python is very slow, so it will be slow to iterate over each point.

**Comment by YueyueBird-su** [comment]
I am uncertain as to how to acquire a dense point cloud using the RPC Model and depth map. Is it due to the depth map being generated by amalgamating disparate blocks after adapting them to the perspective camera?

Initially, I contemplated employing point clouds to derive the necessary DEM-like (height map). However, subsequently, I chanced upon the utility "export_depth_maps_dialog.py" for obtaining the depth map. This led me to ponder _**whether there exists any correlation between the height map and the depth map**_.

Presently, it appears imperative for me to revert to the initial approach of utilizing point clouds to attain the desired outcomes.

I appreciate your response once again, and I extend my best wishes to you.

**Comment by PolarNick239** [comment]
> I am uncertain as to how to acquire a dense point cloud using the RPC Model and depth map.

Just build dense cloud (Workflow -> Build Point Cloud) - using GUI or using ```chunk.buildPointCloud()```

> This led me to ponder whether there exists any correlation between the height map and the depth map.

You will need to unproject each pixel with its depth to 3D to get altitude (which is what you need), so it can be easier to start from dense cloud - because it is already in 3D.

No problems 👌
