### ISSUE TITLE
export model raise problem in mesh Texture

### ISSUE THREAD

**Issue by changfali** [agisoft-llc/metashape-scripts#62]
I used the code below to export model:
    doc = Metashape.Document()
    chunk = doc.addChunk()
    chunk.addPhotos(photos)
    chunk.matchPhotos(keypoint_limit=40000, tiepoint_limit=10000, generic_preselection=True, reference_preselection=True)
    chunk.alignCameras()
    chunk.optimizeCameras()

    chunk.buildDepthMaps(downscale=2, filter_mode=Metashape.MildFiltering)
    chunk.buildModel(source_data=Metashape.DepthMapsData)
    chunk.buildUV(page_count=2, texture_size=4096)
    chunk.buildTexture(texture_size=4096, ghosting_filter=True)
    has_transform = chunk.transform.scale and chunk.transform.rotation and chunk.transform.translation

    if has_transform:
        chunk.buildDenseCloud()
        chunk.buildDem(source_data=Metashape.PointCloudData)
        chunk.buildOrthomosaic(surface_data=Metashape.ElevationData)

    chunk.exportModel(output_folder + "/model.obj", texture_format=Metashape.ImageFormat.ImageFormatPNG)
    chunk.exportCameras(output_folder + "/cameras.xml")

    t1 = time.time()
    print("Processing finished, results saved to " + output_folder + ".", t1 - t0)

but the texture is not right:
![m4OZKFi1R4](https://github.com/agisoft-llc/metashape-scripts/assets/68762767/2e0f521f-7ec9-408f-9ba4-4fbfe7931eb4)
can you help me with this problem? @Jean-Roc @VladimirPobedinskiy @PolarNick239 @Vineg @matjash

**Comment by PolarNick239** [comment]
Hi changfali,

is the problem reproducible from GUI without Python scripting?

**Comment by changfali** [comment]
In GUI, I can not export texture:
![71WKdrt2P9](https://github.com/agisoft-llc/metashape-scripts/assets/68762767/0ddcd1e2-0890-408e-80ce-b70af8087206)

those are the steps:
1. add--> Add Photos
2. process--> Align Photos
3. process--> Optimize Cameras
4. Export-->Export Model
![image](https://github.com/agisoft-llc/metashape-scripts/assets/68762767/4ff5686c-1746-4593-8973-d701cacbe054)

**Comment by PolarNick239** [comment]
Please share to support@agisoft.com so that we can reproduce and investigate the problem:

1) example dataset that reproduces the problem
2) script that reproduces the problem on the example dataset
3) steps to reproduce
4) full log of processing these steps on your side
5) version of used Metashape
