### ISSUE TITLE
Issue regarding gcp co-ordinate system 

### ISSUE THREAD

**Issue by maazraan** [agisoft-llc/metashape-scripts#64]
I debugged a code, and printed gcp errors individually, i want to know the unit of these errors. 
GCP 0 - RMSE_X: 0.213748803, RMSE_Y: 0.285612156, RMSE_Z: 0.000000000
GCP 1 - RMSE_X: 0.672572103, RMSE_Y: 0.653956691, RMSE_Z: 0.000000000
GCP 2 - RMSE_X: 0.649858466, RMSE_Y: 0.552218275, RMSE_Z: 0.000000000
GCP 3 - RMSE_X: 0.223301913, RMSE_Y: 0.362567542, RMSE_Z: 0.000000000

I think these are in pixels, if so how to convert them in meters.Also i want the results in UTM co-ordinate system only.

**Comment by PolarNick239** [comment]
Hi,

can you please specify what code printed these values?
