### ISSUE TITLE
export_for_gaussian_splatting.py coordinate Issue

### ISSUE THREAD

**Issue by aaronhdgolf** [agisoft-llc/metashape-scripts#66]
I have a project using WGS / UTM zone 32618 when I export.

the gaussian splatting is jumping all over the place and then settles. This is due to the coordinate system and being very far away from 0,0,0.

I tried changing the coordinate system to local coordinates but the gaussian is just a blurry mess.

**Comment by PolarNick239** [comment]
Hi, updated version of [the script](https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py) includes workaround (```Use localframe``` checkbox):

![image](https://github.com/agisoft-llc/metashape-scripts/assets/1218605/d768f430-9f12-49ed-afd5-7e7f348cec4b)

Can you please try to process your data again?

**Comment by aaronhdgolf** [comment]
Calibrations:
2023-10-10 07:26:53 0 4081.0445893333745 6130 4078 -0.0 -0.0
2023-10-10 07:26:53 Traceback (most recent call last):
2023-10-10 07:26:53   File "D:/export_for_gaussian_splatting_new.py", line 615, in <lambda>
2023-10-10 07:26:53     proc = lambda : self.run_export()
2023-10-10 07:26:53   File "D:/export_for_gaussian_splatting_new.py", line 513, in run_export
2023-10-10 07:26:53     export_for_gaussian_splatting(params, self.pBar)
2023-10-10 07:26:53   File "D:/export_for_gaussian_splatting_new.py", line 489, in export_for_gaussian_splatting
2023-10-10 07:26:53     calibs = compute_undistorted_calibs(frame, params.zero_cxy)
2023-10-10 07:26:53   File "D:/export_for_gaussian_splatting_new.py", line 238, in compute_undistorted_calibs
2023-10-10 07:26:53     calib = compute_undistorted_calib(sensor, zero_cxy)
2023-10-10 07:26:53   File "D:/export_for_gaussian_splatting_new.py", line 161, in compute_undistorted_calib
2023-10-10 07:26:53     left = max(left, pt.x)
2023-10-10 07:26:53 AttributeError: 'NoneType' object has no attribute 'x'

**Comment by PolarNick239** [comment]
Probably this error is not connected with coordinate system - it seems that problem depends on camera calibration. Can you please provide small dataset reproducer to support@agisoft.com ? (with link to this issue) So that we could reproduce and investigate the problem.

**Comment by aaronhdgolf** [comment]
> Probably this error is not connected with coordinate system - it seems that problem depends on camera calibration. Can you please provide small dataset reproducer to [support@agisoft.com](mailto:support@agisoft.com) ? (with link to this issue) So that we could reproduce and investigate the problem.

Send over a link

thanks.

**Comment by PolarNick239** [comment]
[The script](https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py) was updated, we tested it on your dataset. Can you please try once again?

The problem was that the project included spherical camera sensor before - and script wasn't handling such case nice. Now script supports such case - also please note that all non-Frame cameras (including spherical) are just ignored. This is because Gaussian Splatting doesn't support any camera type except regular Frame-camera.

**Comment by CameronFraser** [comment]
@PolarNick239 wdym by non frame cameras? Does that mean the script won't process equirectangular/spherical images? if not why not undistort and rotate the pose so each image and pose becomes 6 images and 6 poses?

**Comment by PolarNick239** [comment]
> Does that mean the script won't process equirectangular/spherical images?

Yes, this is correct.

> If not why not undistort and rotate the pose so each image and pose becomes 6 images and 6 poses?

Yes, this is good idea and it should work. But such improvement requires more time/efforts and thus wasn't implemented - because this feature has low priority (w.r.t. other features and development priorities).

We are open for pull requests if you want to add support for other camera types.

**Comment by aaronhdgolf** [comment]
Would be really great if the export script separated the 360 into separate files for GS.

Because splitting up before agisoft and then aligning takes forever and the alignment is not that great.
