### ISSUE TITLE
export_for_gaussian_splatting.py "Export Images" checkbox

### ISSUE THREAD

**Issue by henrypearce4D** [agisoft-llc/metashape-scripts#68]
Would it be possible to add an "Export Images" checkbox in between "Use localframe" and "Image quality" options?

This would be set to true by default but if you need to quickly export the camera files after modifying something then you don't need to export the undistorted images again.

I've duplicated and modified the script by removing the image export params which works, but I'm having trouble editing the script and adding it to the script options, having it included will be very useful.

**Comment by PolarNick239** [comment]
Implemented in [commit](https://github.com/agisoft-llc/metashape-scripts/commit/fdaebdf9c9314a9c0dead670e5e3a8a932f05438). Note that this change is not in master-branch, but in branch created specially for this change. Because it is not obvious how useful it is for other users.

Can you please specify use-cases when you modify something that doesn't affect undistortion of images?

**Comment by henrypearce4D** [comment]
The use is that sometimes if there are too many images, you cannot train the dataset because run into memory errors, so have to remove images and try again. It's trial and error.

The easiest way is duplicate the chunk, and remove images of your choice, and then only export the camera files again. You can still use the original exported undistorted images folder, any images that are not referenced in the camera files are ignored.

**Comment by henrypearce4D** [comment]
This is working great thanks!

**Comment by Teran72** [comment]
The script exports only enabled images, so you can just disable some instead of duplicating the chunk.

**Comment by henrypearce4D** [comment]
@Teran72 I see a new commit yesterday
https://github.com/agisoft-llc/metashape-scripts/commit/7dcac6a8fc87f538586e6f39a4cc4552cfc73db5

is it possible to update the branch with these changes?
https://github.com/agisoft-llc/metashape-scripts/blob/issue68/src/export_for_gaussian_splatting.py

**Comment by Teran72** [comment]
We merged branch [issue68](https://github.com/agisoft-llc/metashape-scripts/tree/issue68) into the [main](https://github.com/agisoft-llc/metashape-scripts/tree/master) branch instead, now this option is in the Advanced group.
