### ISSUE TITLE
camera calibration export/import for scenes with multiple cameras script?

### ISSUE THREAD

**Issue by henrypearce4D** [agisoft-llc/metashape-scripts#69]
Is there a script for saving camera calibration and loading it for multiple cameras?
![image](https://github.com/agisoft-llc/metashape-scripts/assets/106480554/fe5d152d-863b-439e-a5e4-8f86f1002a41)
![image](https://github.com/agisoft-llc/metashape-scripts/assets/106480554/90253a99-be82-4aa1-bda5-9ac7377766a4)

The example shows one camera, is it possible to do this with a script for scenes with say 50 -200 different cameras (sensors)?

https://agisoft.freshdesk.com/support/solutions/articles/31000160059-lens-calibration-using-chessboard-pattern-in-metashape

**Comment by PolarNick239** [comment]
Hi, how do you match each image with corresponding sensor? Photos taken from the same camera have the same name?

In such case you can use Export Cameras + Import Cameras, so intrinsics (focal length, cx, cy, etc.) and extrinsics (position and orientation) will be loaded. And after that you can reset alignment if you need to get rid of extrinsics - i.e. if you want to find position and orientation of cameras from scratch (but using imported interior parameters).

Also, you can do something similar to [this script](https://www.agisoft.com/forum/index.php?topic=6084.15) - i.e. use Metashape.Calibration.save() and Metashape.Calibration.load() - see [Python API](https://www.agisoft.com/pdf/metashape_python_api_2_0_3.pdf) for details.

**Comment by henrypearce4D** [comment]
Thanks for the info. I did try Export / Export Cameras but the option was greyed out because I already reset the alignment. Good to know I can Import the Cameras with alignment then reset and then re-align.
