### ISSUE TITLE
Metashape.app.document returns NoneType

### ISSUE THREAD

**Issue by OneGneissGuy** [agisoft-llc/metashape-scripts#7]
Every example that calls Metashape.app.document fails because `Metashape.app.document` returns `NoneType`. Expect examples to work as listed in the documentation:

```
import Metashape
chunk = Metashape.app.document.addChunk()
chunk.addPhotos(["IMG_0001.jpg", "IMG_0002.jpg"])
camera = chunk.cameras[0]
camera.photo.meta["Exif/FocalLength"]
Traceback (most recent call last):

  File "<ipython-input-34-087caf902849>", line 2, in <module>
    chunk = Metashape.app.document.addChunk()

AttributeError: 'NoneType' object has no attribute 'addChunk'
```

System specs:
* Windows 10
* Python 3.7.4 64-bit
* Metashape python api version 1.5 2
* I do not have Agisoft Metashape installed

**Comment by PolarNick239** [comment]
You need to create new document and use it instead of the ```Metashape.app.document```:

```
import Metashape
doc = Metashape.Document()
chunk = doc.addChunk()
chunk.addPhotos(["IMG_0001.jpg", "IMG_0002.jpg"])
camera = chunk.cameras[0]
camera.photo.meta["Exif/FocalLength"]
```

This is because ```Metashape.app``` represents Metashape application, and so it is ```None``` in stand-alone python wheel.

And yes, we should update documentation :)

**Comment by nys09** [comment]
I am getting the following error after following your direction and defining the following.
    doc = Metashape.document
AttributeError: module 'Metashape.Metashape' has no attribute 'document'

I am using the following code. Please let me know if I am missing something. Also, please correct other mistakes in the code if there are any.
import os
import Metashape
import numpy as np
pa='/home/nys09/'
pat='/home/nys09/Trial1Beamch_arc/'
b=[]
c=os.path.join(pa,"arc_imagelist_t1.txt")
images = open(c,"r+")
a = np.loadtxt(images,dtype=str)
for i in range(np.shape(a)[0]):
    b.append(pat+str(a[i]))
doc = Metashape.document
chunk = doc.addChunk()
chunk.addPhotos(b)
camera = chunk.cameras[0]
camera.photo.meta["Exif/FocalLength"]
chunk.matchPhotos(accuracy=Metashape.HighAccuracy, generic_preselection=True,reference_preselection=False)
chunk.alignCameras()
doc.save(path = "project.psz", chunks = [doc.chunk])

**Comment by LinshuH** [comment]
@PolarNick239 
I got another issue when use `doc = Metashape.Document()`
When I try to **export** model and camera position by
`doc.open('project.psz')`
`doc.exportCameras()`
`doc.exportModel()`
There is an error, error message is:
> doc.exportCameras(path=path)
AttributeError: 'Metashape.Metashape.Document' object has no attribute 'exportCameras'

I wonder what's the proper way to do the export?

**Comment by PolarNick239** [comment]
As you can see in [documentation](https://www.agisoft.com/pdf/metashape_python_api_1_6_0.pdf) - ```exportCameras``` is a method of ```Metashape.Chunk``` class. So you need to use something like ```doc.chunk.exportCameras()```.

P.S. Please ask questions about generic python scripting (that is not relevant to scripts from this repository) on [forum/Python API](https://www.agisoft.com/forum/index.php?board=17.0).
