### ISSUE TITLE
[Feature Request] export cameras.json in Gaussian Splatting

### ISSUE THREAD

**Issue by sergiobdrl** [agisoft-llc/metashape-scripts#70]
Hi,

While having the `cameras.json` file in 3D gaussian splatting does not seem to be an important requirement for visualizing the scenes, some visualizers do look for the cameras.json file (e.g. NeRFStudio's port https://github.com/yzslab/nerfstudio/tree/gaussian_splatting). It might be useful to export this file too. 
(lines https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py#L332)

**Comment by PolarNick239** [comment]
Hi,

it seems that they already have converter for Metashape projects - see [ns-process-data](https://github.com/yzslab/nerfstudio/tree/gaussian_splatting#4-using-custom-data). Does it work for you?

**Comment by henrypearce4D** [comment]
@sergiobdrl that file is created while training, you can see it located in you project output folder
![image](https://github.com/agisoft-llc/metashape-scripts/assets/106480554/a7117908-a35a-420d-bab9-e23d9134bbfc)

@PolarNick239 That process creates a transforms.json, which is used for camera poses for nerfstudio and instant ngp etc, its a very similar file but naming and formatting is slightly different

**Comment by PolarNick239** [comment]
Great, thanks!

**Comment by Jordan-Pierce** [comment]
@henrypearce4D would you mind clarifying the steps to perfom gaussian-splatting (using the nerfstudio branch) to run train a model using metashape output?

It's clear to me how to run nerfacto with metashape data:

1. Run Metshape alignment
2. Export Cameras
3. Use nerfstudio ns-data-process metashape
4. Run the nerfacto model

However, I'm finding issues with using this export_gaussian_script, as it refers to all cameras as their actual name in the metashape project, and only outputs the images as a single scale (the original). When trying to run ns-train guassian-splat, it wants to downscale the images, but then refers to those as "frame_n".

Would appreciate if you could provide some insight on how to use nerfstudio to run guassian splat from a metashape project without using colmap. Thanks!

**Comment by henrypearce4D** [comment]
@Jordan-Pierce I have only used the colmap model files that this metashape script produces with the original Inria code, I'm yet to test the nerfstudio implementation.

Perhaps the "Processing your own Scenes" section can help?
https://github.com/graphdeco-inria/gaussian-splatting#:~:text=your%20own%20Scenes-,Our%20COLMAP%20loaders,-expect%20the%20following
