### ISSUE TITLE
export_for_gaussian_splatting.py Issue with "cropped/unsupported sensors"

### ISSUE THREAD

**Issue by Miaoing** [agisoft-llc/metashape-scripts#71]
I'd like to express my gratitude for the superb conversion scripts you've provided (export_for_gaussian_splatting.py). The rendering results I've achieved using Metashape significantly outperform those from COLMAP.

Nevertheless, I've encountered a couple of challenges:

Cropped/Unsupported Sensors: On certain occasions, I've noticed "cropped/unsupported sensors" messages, even when Metashape successfully aligns all the images.

Incorrect Projection Values: I've debugged the scripts and printed the "unproject" and "project" values for the "right, left, top, and bottom" parameters. Some inconsistencies have been observed. For instance, the left value is greater than the right, and there are extremely large negative values post-projection.

Given these issues, I have a few questions:

Why might these anomalies be occurring?
Is there a recommended approach to rectify them?
If opting for undistortion leads to fewer views, does the script offer an option to bypass the undistortion step?
I'd appreciate any insights or guidance you can provide on this matter. Thank you in advance!

@PolarNick239

**Comment by PolarNick239** [comment]
Hi,

> Cropped/Unsupported Sensors: On certain occasions, I've noticed "cropped/unsupported sensors" messages, even when Metashape successfully aligns all the images.

1) What kind of "Camera type" do you have in such projects? You can get this information in Tools->Camera Calibrations (clicking on each camera group on the left).

> Incorrect Projection Values: I've debugged the scripts and printed the "unproject" and "project" values for the "right, left, top, and bottom" parameters. Some inconsistencies have been observed. For instance, the left value is greater than the right, and there are extremely large negative values post-projection.

2) Can you please provide a dataset for internal usage (to [support@agisoft.com](mailto:support@agisoft.com) with link to this github issue) so that we will be able to reproduce the problem to investigate it?

> If opting for undistortion leads to fewer views, does the script offer an option to bypass the undistortion step?

3) No, because Colmap project file structure supports only part of distortions parameters that are used in Metashape. So we need to transform image to camera model that is supported in Colmap project fully.

**Comment by Miaoing** [comment]
Hi,
> What kind of "Camera type" do you have in such projects? You can get this information in Tools->Camera Calibrations (clicking on each camera group on the left).
1. The 'Camera type' is frame. All the images are captured using a camera dome at the same time. All the cameras are of the same type but different zooms.
> Can you please provide a dataset for internal usage (to [support@agisoft.com](mailto:support@agisoft.com) with link to this github issue) so that we will be able to reproduce the problem to investigate it?
2. Yes. I have sent the data to the mail.  And we have observed that, by changing 'Key point limit' and 'Tie point limit', in 'Align Photos', we can find an optimal case where all the photos can be exported. But in the default setting, there will be missing photos after exporting.

**Comment by Teran72** [comment]
Hi,

In your case you have several small calibration groups. Calculated intrinsic parameters for them weren't reliable and caused that anomalies. Increased point limits resulted in better intrinsics.

We recommend to use "Adaptive camera model fitting" option at the alignment step -- Metashape will try to identify unreliable parameters and won't optimize them.

Also Gaussian Splatting software isn't considering cx and cy parameters (at least yet):
https://github.com/graphdeco-inria/gaussian-splatting/issues/144
https://github.com/graphdeco-inria/gaussian-splatting/issues/399
Our script tries to bypass that by cropping the image during the undistortion step (Enforce zero cx, cy checkbox), so undistorted image will have principal point at the center. It can result in large cropping if cx and cy are large enough.

In that case you can manually disable cx/cy optimization and set them to zero. It can be done by (before alignment step):
Tools -> Camera Calibration... -> select all calibration groups at the left panel -> Fixed parameters: -> Select... -> check "cx, cy"
Also ensure that every calibration group in Camera Calibration window has zero cx and cy at the Initial tab
