### ISSUE TITLE
CHECK photo path and skip / export gaussian splatting

### ISSUE THREAD

**Issue by antoinebio** [agisoft-llc/metashape-scripts#73]
Hello @PolarNick239 

would it be possible to skip broken image path in PSX when using that export gaussian splatting script ?

something like that ?

<img width="354" alt="image" src="https://github.com/agisoft-llc/metashape-scripts/assets/30265851/c99de49f-bbf0-47e6-a1d4-2e9e6d89288c">

Here frame.photo.path is not working but this is the idea.
either with a dedicated function or with a modification like that.

**Comment by PolarNick239** [comment]
Hi, yes, something like this should work. Note that you need to check ```cameras``` (not ```frames```), and probably ```camera.image()``` (see [Python API reference](https://www.agisoft.com/pdf/metashape_python_api_2_1_0.pdf)) - can help you to "try to load the image" - to check if it succeed or not.

**Comment by antoinebio** [comment]
agisoft support gave me some tips, see below for camera removal.

camera disable could be an option, but I don't know if it's causing issue when image is disable in export gaussian splatting python script.

*******************************************************
import os, Metashape
chunk = Metashape.app.document.chunk
remove_cameras = []
for camera in chunk.cameras:
   if camera.type != Metashape.Camera.Type.Regular:
      continue #skipping animation cameras if any
   if not os.path.isfile(camera.photo.path):
      remove_cameras.append(camera)
      continue
   if not os.path.exists(camera.photo.path):
      remove_cameras.append(camera)
      continue
chunk.remove(remove_cameras)
