### ISSUE TITLE
Feature Request:Neus camera format

### ISSUE THREAD

**Issue by Michaelwhite34** [agisoft-llc/metashape-scripts#76]
The colmap created by the Gaussian splatting can be used by img2poses.py in https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data. However, in most cases it will cause "Don't need to run COLMAP
Post-colmap
Cameras 5
Images # 35
Traceback (most recent call last):
  File "E:\dataprep\imgs2poses.py", line 17, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "E:\dataprep\pose_utils.py", line 264, in gen_poses
    save_poses(basedir, poses, pts3d, perm)
  File "E:\dataprep\pose_utils.py", line 67, in save_poses
    cams[ind-1] = 1
IndexError: list assignment index out of range" Or 

"Don't need to run COLMAP
Post-colmap
Cameras 5
Images # 55
ERROR: the correct camera poses for current points cannot be accessed
Done with imgs2poses". This means that the output is different from standard colmap output.

**Comment by PolarNick239** [comment]
Hi! Thanks for your detailed request! Just so that you're aware - currently we don't have plans on this (w.r.t. other features and development priorities).
