### ISSUE TITLE
Gaussian splatting script does not include all tie points (?)

### ISSUE THREAD

**Issue by shiukaheng** [agisoft-llc/metashape-scripts#78]
I am using the Gaussian Splatting export script but it seems like all the `point3d_id`'s referenced in `points3D.txt` do not exist in the IDs in `images.txt`. However I am not familiar enough with the Metashape API to figure out what the issue is. I would continue to look into this but would appreciate any help in the meantime, thanks!

Attached are some sample reconstruction files demonstrating the issue; I have converted it to .txt format for easy reading.
[images.txt](https://github.com/agisoft-llc/metashape-scripts/files/14240130/images.txt)
[points3D.txt](https://github.com/agisoft-llc/metashape-scripts/files/14240132/points3D.txt)

**Comment by Teran72** [comment]
Thank you for the report, we have fixed that.

**Comment by graveyard99** [comment]
This script only exports Master cameras.

Right now I have 700 Master cams, each with 5 Slave cams, so in total I should have access to 3500 cams for GS… I hope that makes sense

Looking at the scripting documentation here:
http://download.agisoft.com/metashape-java-api/latest/com/agisoft/metashape/Chunk.html

Seems like I need to do something like this, but unsure how exactly, as  I’m a total Python noob:

To export the slave/secondary cameras, I’ll need to modify the parts of the script that iterate over the cameras in each chunk/frame. Specifically, in the functions “get_filtered_track_structure”, “save_undistorted_images”, and “save_images”, i’lll need to iterate over not just “frame.cameras” but also “frame.camericaclusters” which contains the slave camera clusters.

For each slave camera cluster, I’ll need to extract the individual slave cameras using “cluster.cameras” and process them similar to how the primary cameras are processed.

Can we get this updated in the script so Multicam users can enjoy GS too? Would help people in the VFX and Surveying industry a great deal!

**Comment by PolarNick239** [comment]
Hi @graveyard99, please [create a new issue](https://github.com/agisoft-llc/metashape-scripts/issues/new/choose) so that it will be easier not to get entangled in discussions.

Also, please share a project-reproducer to [support@agisoft.com](mailto:support@agisoft.com) with steps to reproduce (probably just "open the project -> launch the script"), so we were able to reproduce and investigate the problem. Probably small part of the project will be enough - just make sure that it can reproduce the problem.
