### ISSUE TITLE
Location of older Python API Wheels?

### ISSUE THREAD

**Issue by Jordan-Pierce** [agisoft-llc/metashape-scripts#79]
Hi,

We have some scripts that use an older version of the Metashape API; some users are using newer versions of the API which causes the scripts to fail. We plan to update the scripts, but for ease we'd also just like to point users to the wheels of the versions we used.

I cannot find the URL containing the wheel for Windows and Linux version 1.8.4, nor can I find a page that easily provides links to all previous releases.

thanks

**Comment by PolarNick239** [comment]
Hi, you can get URL via [web.archive.org](https://web.archive.org/web/20220501000000*/https://www.agisoft.com/downloads/installer/), f.e. on [this page (JUN 15 2022)](https://web.archive.org/web/20220615095118/https://www.agisoft.com/downloads/installer/) you can get 1.8.3 wheel URL, and after replacing 1.8.3 with 1.8.4 you can get URLs for 1.8.4:
- https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-1.8.4-cp35.cp36.cp37.cp38-abi3-linux_x86_64.whl
- https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-1.8.4-cp35.cp36.cp37.cp38-none-win_amd64.whl

**Comment by Jordan-Pierce** [comment]
That works, thanks!
