### ISSUE TITLE
The gaussian result using export script with checkbox Use Localframe unchecked was bad.

### ISSUE THREAD

**Issue by anonymouslosty** [agisoft-llc/metashape-scripts#80]
Hi！I tired the script export_for_gaussian_splatting.py with the checkbox Use Localframe unchecked. The export result looks fine.But when i use it to train my scene. The coordinate seems to be bad. Could you tell me the situation when i should leave the Use Localframe unchecked? Thanks!
![NotUseLocalframe](https://github.com/agisoft-llc/metashape-scripts/assets/107968327/636a3d24-17d7-408f-9619-1da119fb526b)
@PolarNick239

**Comment by Teran72** [comment]
Hi!
The "Use localframe" option has been added for datasets that have huge coordinates after the export (Gaussian Splatting may fail in such cases, as in issue #66)
You may want to uncheck this option if you want the absolute coordinates to remain unchanged (as in Metashape)

**Comment by anonymouslosty** [comment]
Thanks a lot! It solves my problem! @Teran72
