### ISSUE TITLE
Colmap database

### ISSUE THREAD

**Issue by fifi1ous** [agisoft-llc/metashape-scripts#82]
Hi, I have stumbled upon the Jawset Postshot, in which you can create a 3DGS model, can I get from this script a .db file?

**Comment by PolarNick239** [comment]
Hi, no, script export_for_gaussian_splatting.py doesn't export .db file

**Comment by fifi1ous** [comment]
I worked it out with the support of the Jawset Postshot. You don't need a db. file like is written in the app, just drag and drop the whole file.

**Comment by henrypearce4D** [comment]
@fifi1ous 
"The .db file is not used. It's just an alternative way to indirectly select the reconstruction folder. You can also drop the 'sparse' folder or one of its subfolders directly. It will only need the 3 .bin files."
https://discord.com/channels/1177235109162799105/1209912158020968469/1210177603089072148

Select your images folder and sparse folder and drag and drop them into postshot. There was an update to fix colmap models from this script and it all works now.
