### ISSUE TITLE
how to update points if camera removed before export ?

### ISSUE THREAD

**Issue by cyrilpreiss** [agisoft-llc/metashape-scripts#83]
i'm doing some test to combine the use of Metashape and gaussian splatting.
Exporting camera algignement data with the python script is working well.

But if i remove cameras from the project (because gaussian splatting need all cameras to be the same and same focal lenght) and make the export, the exported points still contains points from the removed cameras and this is create errors in gaussian splatting training.

Is there a way to "clean" the point cloud after having removed the cameras and before running the script ?

i wouldn't want to start alignment from scratch...

**Comment by PolarNick239** [comment]
>  exported points still contains points from the removed cameras and this is create errors in gaussian splatting training

Hi, could you please share the text of the error message from gaussian splatting?
