### ISSUE TITLE
Metashape Agisoft 1.5.2 Script for Gaussian Splatting

### ISSUE THREAD

**Issue by DuVogel87** [agisoft-llc/metashape-scripts#88]
Is this script also available for my older version of metashape 1.5.2?

**Comment by PolarNick239** [comment]
Hello!

No, this script was introduced in Metashape 2.0 (the 2.0 version is available in the [2.0 branch](https://github.com/agisoft-llc/metashape-scripts/tree/2.0/src)), so it has only been tested with Metashape versions 2.0 and 2.1.

So I can recommend you to upgrade Metashape to version 2.0 or 2.1. Note that you don't need to buy a new license - your old one is fine - see [**note** here](https://www.agisoft.com/downloads/installer/).
