### ISSUE TITLE
Script export usable with Jawset Postshot

### ISSUE THREAD

**Issue by DuVogel87** [agisoft-llc/metashape-scripts#89]
Can the script export be used with Jawset Postshot? And if so, could you please give a short explanation on how to? Thanks!

**Comment by PolarNick239** [comment]
Hello!

Sorry, I don't know anything about Jawset Postshot. When I look at the [Documentation](https://www.jawset.com/docs/d/Postshot+User+Guide/Interface/Main+Tools), it seems that you can try to import:
- ```.PLY files with Gaussian Splatting data```
- ``COLMAP databases with tracked camera and point data`` (I don't know what they mean, maybe cameras.bin and points3D.bin)

**Comment by DuVogel87** [comment]
The export of this script gives me a sparse folder with cameras, images and points3D.bin 
Screenshot:
![sparse](https://github.com/agisoft-llc/metashape-scripts/assets/123517103/03450a40-c5de-42f1-a237-49ce44b5abbe)

When i look at the sparse folder created from colmap i get a cameras, images and points3D.bin and a points3D.ply (i believe the last one is not so important right now)
Screenshot: 
![sparse colmap](https://github.com/agisoft-llc/metashape-scripts/assets/123517103/89b943d9-4870-4e34-90ca-02a1e0d90c37)

I believe that the issues is in the images.bin. The images.bin from this script creates a 1 KB file size which seems not to be correct for me?

Do you have any thoughts on this for me? Thanks.

**Comment by DuVogel87** [comment]
also one screenshot to show what i did before i run the script

![Uploading screenshot agisoft.PNG…]()

**Comment by henrypearce4D** [comment]
@DuVogel87 Best to join the discord if you are not already
https://discord.gg/5Zat4Gbw

The metashape script creates a colmap model format that works perfectly with postshot 

Just simply select both your images and sparse folder and drag and drop them into the postshot main window and ensure that Camera Poses is set to Import

![image](https://github.com/agisoft-llc/metashape-scripts/assets/106480554/2332e8aa-d3ec-4327-a43b-daa2c3475f94)


![image](https://github.com/agisoft-llc/metashape-scripts/assets/106480554/3e84d638-6796-4047-a1e0-ff9e5dcd9291)

**Comment by PolarNick239** [comment]
> The metashape script creates a colmap model format that works perfectly with postshot

That's great. Thanks, Henry!

@DuVogel87
> I believe that the issues is in the images.bin. The images.bin from this script creates a 1 KB file size which seems not to be correct for me?
> Do you have any thoughts on this for me? Thanks.

Have you tried to process with original Gaussian Splatting implementation (see [instructions](https://github.com/PolarNick239/gaussian-splatting-Windows/tree/main?tab=readme-ov-file#preparing-images-from-your-own-scenes-agisoft-metashape-pro)) or with PostShot following Henry's instructions?

If you have tried - what kind of error/problem did you encounter?

**Comment by DuVogel87** [comment]
When I export the images folder is empty, even though i checked mark export images. And also the images.bin is only 1 KB in size. 

Do I have to select something in the editor so that metashape script knows more precisely what to export?

**Comment by henrypearce4D** [comment]
The images.bin being small file size is an issue yes, it should a list of images and the tie points.

Are all your images enabled before export? 

Also what type of images are they? they have to be "Frame" type not "Fisheye", check this info in this issue here;

https://github.com/agisoft-llc/metashape-scripts/issues/84#issuecomment-2100336459

**Comment by PolarNick239** [comment]
> When I export the images folder is empty

Please share a project-reproducer to [support@agisoft.com](mailto:support@agisoft.com) with steps to reproduce (probably about running the script), so we were able to reproduce and investigate why there are no images output. Probably small part of the project will be enough - just make sure that it can reproduce the problem.

**Comment by DuVogel87** [comment]
![colmap export settings](https://github.com/user-attachments/assets/24e3ff04-4106-4386-9fef-605ef44a3dd2)
![iamges](https://github.com/user-attachments/assets/90becd49-c5d0-4103-9a57-19710a725c74)
![sparse](https://github.com/user-attachments/assets/04c85cfc-88fc-4945-8ce4-c7dd7043bf2a)
![jawset failed](https://github.com/user-attachments/assets/327be95c-4c10-467c-9781-a8702ff60f80)

**Comment by DuVogel87** [comment]
here is a wetransfer link to my .psx file. Thanks for the help!

**Comment by DuVogel87** [comment]
Pardon. I just recently became father and am too tired sometimes ^^ 

Here's the link: https://we.tl/t-qenCg7ZhHT

**Comment by DuVogel87** [comment]
Solved it! I did a new alignment from scratch and then it worked.

**Comment by DuVogel87** [comment]
Now the error is back. I tried another set of images. Aligned them in a new scene in metashape, exported them with the script, again no images and 1KB images.bin. 

Trying to figure out what am i doing wrong

**Comment by DuVogel87** [comment]
Okay. I am not able to export it. I tried it several times again. As i wrote, i was able to export succesfully one time but not any more. Really i have no idea whats going on because i dont see any difference in my process. I even downloaded the script new to see if this can solve my problem. it did not. 

so here is my project file. the download link includes the .psx file and the .files folder. its around 60mb in size. 
i would highly appreciate every kind of help here. i am on a 30 day test version of metashape and already have spent 4 days with trying to get this script running!! 

i tried to execute the script via windows key + r and loaded it. and i also tried the way to put the script in the scripts folder within appdata and so. 

the one time it worked i used the way with the windows key + r to execute the script.

please help :)

wetransfer link; https://we.tl/t-ZQ3gQMzkuW

**Comment by DuVogel87** [comment]
Okay, so here is my update. Today it worked again. I was able to recreate the solution by restarting my pc every time i wanted to align something in metashape and export. Has this something to do with the 30 day trial version? i dont know. but i am glad it works now.

So one last thing. when i export from metashape to postshot and train, everything is upside down. Even though in metashape everything is on the right side. If anybody can tell me something to this i would appreciate it. Thanks!

**Comment by henrypearce4D** [comment]
It's probably the coordinate system difference and not really an issue, in postshot you can go to the right menu / edit and rotate the model and even save it out by going to File /Export Splat Model

**Comment by PolarNick239** [comment]
@DuVogel87 
Thanks for providing the project, we will investigate the problem (why no images were exported) and come back with the results.

**Comment by PolarNick239** [comment]
No images were exported due to problematic calibration (too high distortion errors):
![image](https://github.com/user-attachments/assets/eb92bdf9-eaf5-43c6-8a08-d7a8d30495a2)

We improved [the script](https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py) so that now it can handle even such cases, can you please confirm that it works for you now?

**Comment by DuVogel87** [comment]
Thanks for improving the script. Still i struggle with the script. Sometimes the export works, sometimes not. Now i have the situation that it doesnt work at all. I made a 1:15 minute long video (screen capture) which shows exactly my issue. Hope there is a very simple solution to it. I really spent half of the test-trial so far not working with metashape because it freaks me out, that such a simple action does not work properly. But i really appreciate the speed of the support here!

**Comment by DuVogel87** [comment]
https://we.tl/t-EO1PeZ1p23

**Comment by PolarNick239** [comment]
I generated low-res photos from thumbnails in .psx project that you provided earlier, and executed the script twice - it executed OK on both runs and all 492 cameras were exported - see log from Console tab:

```
2024-07-22 12:07:04 Cropped initial calibration due to high distortion 5210x3474 -> 3965x3304
2024-07-22 12:07:04 Calibrations:
2024-07-22 12:07:04 0 2179.6233008185627 5606 4014 0.0 0.0
2024-07-22 12:07:20 Found 828281 cropped projections
2024-07-22 12:07:20 Exporting images.
2024-07-22 12:12:29 Undistorted 492 cameras
2024-07-22 12:12:29 Saved 1 calibrations
2024-07-22 12:12:34 Saved 492 cameras
2024-07-22 12:12:40 Saved 553998 points from 907182 tracks
2024-07-22 12:12:40 
2024-07-22 12:12:40 Done
2024-07-22 12:12:40 -----------------------------------
```

Also undistorted image looks good (it is low-res because original image was generated from low-res thumbnail):

![image](https://github.com/user-attachments/assets/15bf0c07-6920-4c9a-a7df-685c2fe33f62)

Are you sure you have run the new version of the script? (It's easy to confuse because the file with the old version has the same name)

If you are sure and it doesn't work for you, please copy and send the text from the Console panel (similar to what I provided above), and send the .psx project on which it doesn't work (along with the .files folder) so that we can reproduce and investigate the issue.

**Comment by Vineg** [comment]
Hi, @DuVogel87

Colmap format doesn't support spherical camera calibration. And spherical panoramas can't be easily represented with other camera models.
If you have original photos before stitching them to spherical panoramas - please use them.

Regards, Egor

**Comment by PolarNick239** [comment]
> I really spent half of the test-trial so far

Regarding the trial license - please write to [support@agisoft.com](mailto:support@agisoft.com) with a reference to this discussion, and we will be happy to extend your trial key.

**Comment by DuVogel87** [comment]
Already did, and already received. Such nice people.

But whats wrong with the script?

⁣BlueMail for Android herunterladen ​

**Comment by DuVogel87** [comment]
> Hi, @DuVogel87
> 
> Colmap format doesn't support spherical camera calibration (you pick it on a video). Gaussian splatting software may not support this type of calibration as well. Spherical panoramas can't be easily represented with other camera models.
> If you have original photos before stitching them to spherical panoramas - please use them.
> 
> Regards, Egor

I don't get it. Agisoft Metashape is well known for being able to work with 360 images. That's what I imported in my video, as you pointed out rightly.

So when alignment is done it want to execute the export script. Do i understand you right, that the reason why the export doesn't work is, because of the 360 images I used to import?

That wouldn't make sense to me. 

Please can you explain to me what you mean a bit more because I think I dont got it.

**Comment by DuVogel87** [comment]
> I generated low-res photos from thumbnails in .psx project that you provided earlier, and executed the script twice - it executed OK on both runs and all 492 cameras were exported - see log from Console tab:
> 
> ```
> 2024-07-22 12:07:04 Cropped initial calibration due to high distortion 5210x3474 -> 3965x3304
> 2024-07-22 12:07:04 Calibrations:
> 2024-07-22 12:07:04 0 2179.6233008185627 5606 4014 0.0 0.0
> 2024-07-22 12:07:20 Found 828281 cropped projections
> 2024-07-22 12:07:20 Exporting images.
> 2024-07-22 12:12:29 Undistorted 492 cameras
> 2024-07-22 12:12:29 Saved 1 calibrations
> 2024-07-22 12:12:34 Saved 492 cameras
> 2024-07-22 12:12:40 Saved 553998 points from 907182 tracks
> 2024-07-22 12:12:40 
> 2024-07-22 12:12:40 Done
> 2024-07-22 12:12:40 -----------------------------------
> ```
> 
> Also undistorted image looks good (it is low-res because original image was generated from low-res thumbnail):
> 
> ![image](https://github.com/user-attachments/assets/15bf0c07-6920-4c9a-a7df-685c2fe33f62)
> 
> Are you sure you have run the new version of the script? (It's easy to confuse because the file with the old version has the same name)
> 
> If you are sure and it doesn't work for you, please copy and send the text from the Console panel (similar to what I provided above), and send the .psx project on which it doesn't work (along with the .files folder) so that we can reproduce and investigate the issue.

Dear Nick,
Did you see the video above I uploaded via wetransfer?
Thanks for your time. I figured that the scene you looked at works fine with the script. 
But in my video I am showcasing a different situation which causes trouble.
If you could have a look at it I would appreciate it!
Thanks.

**Comment by PolarNick239** [comment]
> Agisoft Metashape is well known for being able to work with 360 images. ... Do i understand you right, that the reason why the export doesn't work is, because of the 360 images I used to import?

Yes, the processing of spherical photos in Metashape works fine.

But Gaussian Splatting doesn't support any camera type except regular Frame-camera. So the export_for_gaussian_splatting.py ignores all non-Frame cameras (including spherical).

> Did you see the video above I uploaded via wetransfer?

Yes, I missed that you tries to process spherical cameras, as @Vineg told - sadly such cameras are not supported in Gaussian Splatting, so the script skips them.

**Comment by DuVogel87** [comment]
Okay. Now I understand. Perfect.

Then I know what to do next. Thanks for the help so far!

**Comment by PolarNick239** [comment]
Nice. As Vineg said - maybe processing two fisheye source images instead of 360-photos would help (for example, this is possible on Insta360 cameras), or you can try to find a tool that can split one 360-photo into 6 pinhole-photos (like in cube mapping).

Anyway, if you find a solution, please post a comment here - it will be useful for other users with similar problem.

**Comment by DuVogel87** [comment]
There is this Youtuber who programed a 360 to square converter. I have tried it and it works perfectly. The 360 image can be split into 2 or 6 (cube mape) images. The youtube video from him is here: https://youtu.be/hX7Lixkc3J8?si=XvgLGXNBfZgmQpAw

In his video description you find the download link for the tool. No malware or such bullshit!

And I think if you familiar with nerfstudio that there is a option to split 360 images into cube map images. But haven't tried it  myself. Just found it in the documentation: https://docs.nerf.studio/quickstart/custom_dataset.html#data

What you said about 2 fisheye images with a insta360 is new to me? Do you have some further details about it?

**Comment by PolarNick239** [comment]
> What you said about 2 fisheye images with a insta360 is new to me? Do you have some further details about it?

Unfortunately, I have no first-hand experience. I found that there are problems with DNG photos - https://www.reddit.com/r/Insta360/comments/1clkrnx/need_help_extracting_dual_fisheye_images_from_dng/

However, some users seem to be able to process data - https://www.agisoft.com/forum/index.php?topic=16091.0

[Here](https://panoraven.com/blog/en/360-best-cameras/) it seems that this is indeed possible:
![image](https://github.com/user-attachments/assets/55f5653a-d315-405f-ba5d-7b8ad1e5fd38)

**Comment by henrypearce4D** [comment]
@DuVogel87 I did mention the images cannot be fisheye above https://github.com/agisoft-llc/metashape-scripts/issues/89#issuecomment-2222473513

you could try splitting your images first with ffmpeg
https://gist.github.com/jo-chemla/a92a54ea06d0a55c9caf62bb532e6f69

**Comment by PolarNick239** [comment]
@DuVogel87 @henrypearce4D 
> they have to be "Frame" type not "Fisheye"
> the images cannot be fisheye

Note that on July 19 we [updated](https://github.com/agisoft-llc/metashape-scripts/commit/29a5041a103e1e912c9ef59b7fe184cb88d0df40) the script so that it now supports fisheye images - it will also undistort them to Frame (i.e. Pinhole) camera.

I will comment on this in the relevant issues in which the Frame-restriction was mentioned.

**Comment by DuVogel87** [comment]
360degree solution anywhere around the corner? Metashape can align them but the export script seems not to work in this "360" case.

**Comment by veosys** [comment]
>360-degree solution
Try Splatica.com for Insta360 cameras
