### ISSUE TITLE
footprints_to_shapes.py won't work on film camera with fiducial marks

### ISSUE THREAD

**Issue by jakeslyder** [agisoft-llc/metashape-scripts#9]
I'm trying to run the footprints to shapes script on older aerial imagery processed using the fiducial marks.  I've replaced line 48 to get the pixel coordinates (rounded to the nearest integer) of the fiducial marks in the four outer corners, but the process on line 49 produces coordinates that form a much smaller footprint, often with coordianates that are nearly on top of each other.  The script works great on older film imagery I've rotated and cropped in photoshop, so I'm thinking I may need another translational step to account for image rotation and scaling based on the fiducial marks?  Any suggestions?  FYI, I've been trying this in 1.5.2 and 1.5.3

Thanks.

**Comment by PolarNick239** [comment]
Please try script with updated [lines 49 and 51](https://github.com/agisoft-llc/metashape-scripts/commit/7432fea4a1271bfbcecf5d5e76109090156c00ae#diff-89aff4a2886797022c0361cbce0e86ccR49):

```camera.transform.mulp(sensor.calibration.unproject(...))```
replaced with
```camera.unproject(...)```

**Comment by jakeslyder** [comment]
Yes, that fixes it . Thank you!
