### ISSUE TITLE
Automated script for multiple camera inputs without gui

### ISSUE THREAD

**Issue by luoshuiyue** [agisoft-llc/metashape-scripts#90]
Hi~ May I ask the export_for_gaussian_splatting.py and general_workflow.py scripts can support multiple camera input, because the default is the same camera parameter to estimate pose. Because I wanted to automate pose estimation using only this script without the need for human interaction gui.

**Comment by PolarNick239** [comment]
Hi, what do you mean by multiple cameras input? Do you mean that some of the photos were taken with one camera and some of the photos were taken with another camera?

If so, it probably should work (just make sure that photos have the correct EXIF tags so general_workflow.py can guess camera groups correctly automatically). Have you tried to process such data? What problems do you encounter?

> the default is the same camera parameter to estimate pose

What do you mean?

**Comment by luoshuiyue** [comment]
> the default is the same camera parameter to estimate pose
What I mean is that my input data (a total of 388 images) is three cameras of the same type (the same type but made in slightly different), and the script will assume that the data set containing three cameras of the same type is from a camera and will only estimate one camera parameter (The algorithm should estimate three camera parameters if the dataset comes from three cameras).
Below are images captured by three cameras and I performed a dedistortion operation :
![023](https://github.com/user-attachments/assets/8b480627-e313-43dd-9a41-c39946f247b4)
![138](https://github.com/user-attachments/assets/b38f0737-161d-4668-b375-b1b14dfb930f)
![255](https://github.com/user-attachments/assets/626a83a4-d6d0-448b-9997-8ba3eccc8027)
![023_undistort](https://github.com/user-attachments/assets/b72891a2-494e-4caf-9104-dc19cba974b6)
![138_undistort](https://github.com/user-attachments/assets/6f73fc41-129d-4cfc-b13c-458a089f4ee4)
![255_undistort](https://github.com/user-attachments/assets/71970e62-e93b-4dbd-826d-d8d03a72f07f)
And the execution result is below:
![微信图片_20240719102518](https://github.com/user-attachments/assets/b7a50815-6c0f-4912-8f2c-9355a23e76d1)

**Comment by PolarNick239** [comment]
Did I understand you correctly that if you were doing the processing in the interface, it would be fine to click Tools->Camera Calibration before aligning the photos, then right click on each group to split it into separate calibration groups (to optimize the internal parameters for each photo independently, since it's a separate camera)?

![image](https://github.com/user-attachments/assets/dfd0d5b3-f2de-4e8a-8118-f6f4631a14b6)

Can you please try doing that in the GUI, then proceed with Align Photos->export and see if the result works for you?


If everything OK - then you need to split cameras into separate calibration groups (for each photo - its own group) automatically via Python API like in this script - https://www.agisoft.com/forum/index.php?topic=4769.0

**Comment by luoshuiyue** [comment]
Hello, I also want to ask the metashape automation processing script to automatically estimate camera parameters and distortion coefficient, may I ask how to add parameters in the automation script to make the distortion fixed or not consider the distortion, is to set the fixed_params parameter, how to use it?

**Comment by PolarNick239** [comment]
> how to make the image resolution does not change after the distortion

Replace function [compute_undistorted_calib(...)](https://github.com/agisoft-llc/metashape-scripts/blob/fc57b5c664af6cc2478d3d6093af4ee2c23904ac/src/export_for_gaussian_splatting.py#L277-L342) with:

```python
def compute_undistorted_calib(sensor, zero_cxy):
    border = 0 # in pixels, can be increased if black margins are on the undistorted images

    if sensor.type != Metashape.Sensor.Type.Frame and sensor.type != Metashape.Sensor.Type.Fisheye:
        return (Metashape.Calibration(), Metashape.Matrix.Diag([1, 1, 1, 1]))

    calib_initial = sensor.calibration
    w = calib_initial.width
    h = calib_initial.height
    f = calib_initial.f

    calib = Metashape.Calibration()
    calib.f = f
    calib.width = w
    calib.height = h

    return (calib, Metashape.Matrix.Diag([1, 1, 1, 1]))
```

Note that without cropping, black pixels may appear at the edge of the image - and Gaussian splatting works poorly with them.
