### ISSUE TITLE
postshot 

### ISSUE THREAD

**Issue by exedesign** [agisoft-llc/metashape-scripts#95]
I use postshot for gsplatler but with this script all my outputs are coming in reverse axis into postshot so is there a way to change this to -y? maybe a menu option

**Comment by exedesign** [comment]
> I use postshot for gsplatler but with this script all my outputs are coming in reverse axis into postshot so is there a way to change this to -y? maybe a menu option
export_for_gaussian_splatting.py

**Comment by henrypearce4D** [comment]
You can edit/rotate in postshot quite easily. 

If you want to correct it in metashape you can rotate the scene.

**Comment by exedesign** [comment]
> Postshot'ta düzenleme/döndürme işlemini oldukça kolay bir şekilde yapabilirsiniz.
> 
> Eğer metashape'te düzeltmek isterseniz sahneyi döndürebilirsiniz.

When I do this via postshot, I encounter both processing time and some strange artifacts. It seems more logical to try it from within metashape, thank you.

**Comment by henrypearce4D** [comment]
you can also try rotation the colmap model with this tool
https://github.com/JohannesKrueger/pointcloudeditor
demo project here;
https://www.panoton.de/tools/pointcloud-editor/

**Comment by PolarNick239** [comment]
Hi, @exedesign !

Is the scene rotated or is the scene mirrored? Can you please illustrate how it looks like in Metashape and in GS? (to visually demonstrate this problem)
