### ISSUE TITLE
export_for_gaussian_splatting.py doe

### ISSUE THREAD

**Issue by cyrilpreiss** [agisoft-llc/metashape-scripts#97]
i'm trying to export cameras from metashape using the python script but it doesn't work, metashape says "run script failed". did i forget an important step i need to do to make it work ? (i have aligned the pics and try to run the script in metashape v2.1)

**Comment by cyrilpreiss** [comment]
i'm trying to export cameras from metashape using the python script but it doesn't work, metashape says  "run script failed". did i forget an important step i need to do to make it work ? (i have aligned the pics and try to run the script in metashape v2.1)

**Comment by PolarNick239** [comment]
Hi, can you please share full log from Console?

![image](https://github.com/user-attachments/assets/1f851ab3-89f8-4d81-981f-6ab614cf5d0f)

**Comment by PolarNick239** [comment]
Also, have you tried the same feature from Metashape GUI?
To do so - install 2.1.3 pre-release and use File Menu -> Export Cameras dialog -> Colmap (*.txt) type
More details: https://www.agisoft.com/forum/index.php?topic=16518.msg71431#msg71431
